matrix:
  include:
    - language: csharp
      before_install:
      - sudo apt-get install nodejs npm
      mono: none
      dotnet: 2.1
      os:
      - linux
      group: dev
      sudo: required
      dist: xenial
      install:
      - npm install -g vsce
      - npm install -g typescript     
      script:
      - cd $TRAVIS_BUILD_DIR/src/Avalonia.Ide.LanguageServer/ ; dotnet restore ; dotnet build --configuration Release
      - cd $TRAVIS_BUILD_DIR/vscode-extension/ ; npm install ; npm pack ; vsce package
      
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file_glob: true
          file: "$TRAVIS_BUILD_DIR/**/*.vsix"
          skip_cleanup: true
      cache:
        directories:
          - node_modules
